### ISSUE TITLE
Scraper Doesnt Have Price Attribute When Running it For AutoTrader website

### ISSUE THREAD

**Issue by mashhype** [Ehsan-U/Cars-Revised#2]
Hi Ehsan,
when running scraper for autotrader, its not showing the price attribute.
<img width="505" alt="Screenshot 2023-11-11 at 1 29 33 PM" src="https://github.com/Ehsan-U/Cars-Revised/assets/4706698/1ed85a8c-7ec7-406e-9384-5250ae489d5f">

**Comment by mashhype** [comment]
I'm seeing the same issue when running scraper for CarGurus listings.

**Comment by Ehsan-U** [comment]
Fixed!
please pull the latest changes.
