### ISSUE TITLE
Unable to load Pandas DataFrame From JSON file after scraping cars dot com listings

### ISSUE THREAD

**Issue by mashhype** [Ehsan-U/Cars-Revised#5]
Hi Ehsan,
I ran the scraper just now for cars.com listings. Got this when trying to load to a pandas dataframe.
<img width="1277" alt="Screenshot 2023-12-10 at 5 59 18 PM" src="https://github.com/Ehsan-U/Cars-Revised/assets/4706698/2586bca5-4c57-43ab-bda7-df3b762a967a">

Also, attaching the urls.csv file.
[urls.csv](https://github.com/Ehsan-U/Cars-Revised/files/13630138/urls.csv)

**Comment by mashhype** [comment]
same thing is happening on CarGurus
![Uploading Screenshot 2023-12-10 at 6.12.15 PM.png…]()

**Comment by Ehsan-U** [comment]
can you try by` json.loads()` method instead pandas and then create Dataframe from that.

**Comment by mashhype** [comment]
<img width="1037" alt="Screenshot 2023-12-11 at 12 46 28 PM" src="https://github.com/Ehsan-U/Cars-Revised/assets/4706698/65fa169a-9980-40c7-9568-0ac838bba839">

Hi @Ehsan-U , getting an error when I use `json.loads()`

**Comment by mashhype** [comment]
Uploading the json file so you can see how its formatted.
[mclaren_cars.json](https://github.com/Ehsan-U/Cars-Revised/files/13642043/mclaren_cars.json)

**Comment by Ehsan-U** [comment]
@mashhype,

When the scraper runs for the first time, it creates a data file containing records of cars. However, if you run the scraper multiple times, it appends the new data to the existing file, which can result in an incorrect JSON format.

To avoid this issue, please make sure to move or rename the existing file before running the scraper again. Otherwise, the scraper will either overwrite or append data to the existing file, potentially causing data format problems.

**Comment by mashhype** [comment]
Ok, I understand what you mean, @Ehsan-U . Let me re-run scraper with a brand new data.json file.

**Comment by Ehsan-U** [comment]
The issue is not related to scraper: please try this snippet for reading JSON:
```
def read_json():
  try:
      with open(filename, 'r') as file:
          json_data = json.load(file)
      is_valid_json = True
  except json.JSONDecodeError as e:
      error_message = str(e)
      is_valid_json = False
```

**Comment by mashhype** [comment]
> The issue is not related to scraper: please try this snippet for reading JSON:
> 
> ```
> def read_json():
>   try:
>       with open(filename, 'r') as file:
>           json_data = json.load(file)
>       is_valid_json = True
>   except json.JSONDecodeError as e:
>       error_message = str(e)
>       is_valid_json = False
> ```

This is not working @Ehsan-U . See the screen shot.
<img width="1086" alt="Screenshot 2023-12-13 at 4 28 36 PM" src="https://github.com/Ehsan-U/Cars-Revised/assets/4706698/630511cb-23e5-437d-bd6b-3ae867a1e820">

**Comment by mashhype** [comment]
I figured it out with chatGPT. See this conversation (2nd question I asked): https://chat.openai.com/share/27f10c3f-e38d-4321-bae9-725b6a8907dc

**Comment by mashhype** [comment]
<img width="1086" alt="Screenshot 2023-12-13 at 4 33 53 PM" src="https://github.com/Ehsan-U/Cars-Revised/assets/4706698/5f2ee9eb-c46f-41ed-98cd-e36afbe8f458">

**Comment by mashhype** [comment]
Used pd.read_json() to load json file to a dataframe
